[window]
opacity = 0.96

[window.dimensions]
columns = 150
lines = 50

[window.padding]
x = 10
y = 10

[scrolling]
history = 10_000
multiplier = 40

[font]
size = 16

[font.normal]
family = "ZedMono Nerd Font Propo"
style = "Regular"

[font.bold]
family = "ZedMono Nerd Font Propo"
style = "Bold"

[font.italic]
family = "ZedMono Nerd Font Propo"
style = "Italic"

# Dark Pride
# A dark trans pride colour inspired theme

# Primary colors
[colors.primary]
background = '#0d0d1b'
foreground = '#ccccce'

# Colors used for 'custom_cursor_colors'
[colors.cursor]
text = '#bbbbbb'
cursor = '#ff0017'

# Colors 0 through 7
[colors.normal]
black = '#282828'
red = '#ca1444'
green = '#789aba'
yellow = '#b3879f'
blue = '#95569b'
magenta = '#cb6fa1'
cyan = '#fb6e93'
white = '#cf98c1'

# Colors 8 through 15
[colors.bright]
black = '#98218e'
red = '#cb515d'
green = '#5a87b1'
yellow = '#9c61ab'
blue = '#9a77b1'
magenta = '#f2a297'
cyan = '#f4436f'
white = '#ebdbb2'
